const data = [
{
    monarch: 'Pengumpulan Laporan KP/PKL',
    start: new Date(2021, 11, 15),
    end: new Date(2021, 12, 21),
    house: 'Pengumpulan Laporan KP',
},
{
    monarch: 'Pengumpulan Laporan KP/PKL',
    start: new Date(2021, 9, 22),
    end: new Date(2021, 10, 21),
    house: 'Pengumpulan Laporan PKL',
},
{
    monarch: 'Seminar KP/PKL',
    start: new Date(2021, 11, 8),
    end: new Date(2021, 12, 7),
    house: 'Seminar KP',
},
{
    monarch: 'Seminar KP/PKL',
    start: new Date(2021, 9, 15),
    end: new Date(2021, 10, 7),
    house: 'Seminar KP',
},
{
    monarch: 'Sosialisasi 3 : Finishing KP/PKL',
    start: new Date(2021, 11, 1),
    end: new Date(2021, 11, 7),
    house: 'Sosialisasi 3',
},
{
    monarch: 'Sosialisasi 3 : Finishing KP/PKL',
    start: new Date(2021, 9, 8),
    end: new Date(2021, 9, 14),
    house: 'Sosialisasi 3',
},
{
    monarch: 'Formulir evaluasi & feedback PKL',
    start: new Date(2021, 10, 22),
    end: new Date(2021, 11, 1),
    house: 'Evaluasi 3',
},
{
    monarch: 'Formulir evaluasi & feedback PKL',
    start: new Date(2021, 9, 14),
    end: new Date(2021, 9, 23),
    house: 'Evaluasi 2',
},
{
    monarch: 'Formulir evaluasi & feedback PKL',
    start: new Date(2021, 8, 1),
    end: new Date(2021, 8, 10),
    house: 'Evaluasi 1',
},
{
    monarch: 'Pelaksanaan PKL (D4)',
    start: new Date(2021, 7, 1),
    end: new Date(2021, 10, 31),
    house: 'Pelaksanaan PKL (D4)',
},
{
    monarch: 'Formulir evaluasi & feedback KP',
    start: new Date(2021, 9, 5),
    end: new Date(2021, 9, 14),
    house: 'Pelaksanaan KP (D3)',
},
{
    monarch: 'Pelaksanaan KP (D3)',
    start: new Date(2021, 7, 1),
    end: new Date(2021, 9, 14),
    house: 'Pelaksanaan KP (D3)',
},
{
    monarch: 'Pembekalan dan Pelepasan',
    start: new Date(2021, 6, 15),
    end: new Date(2021, 6, 21),
    house: 'Pembekalan dan Pelepasan KP/PKL',
},
{
    monarch: 'Persiapan acara',
    start: new Date(2021, 6, 1),
    end: new Date(2021, 6, 14),
    house: 'Persiapan acara pembekalan dan pelepasan',
},
{
    monarch: 'Sosialisasi 2',
    start: new Date(2021, 6, 1),
    end: new Date(2021, 6, 7),
    house: 'Sosialisasi 2 : Penetapan hasil mapping dan dosen pembimbing',
},
{
    monarch: 'Pemilihan dosen pembimbing',
    start: new Date(2021, 6, 1),
    end: new Date(2021, 6, 7),
    house: 'Pemilihan dosen pembimbing KP/PKL',
},
{
    monarch: 'Penanganan pembatalan',
    start: new Date(2021, 5, 22),
    end: new Date(2021, 6, 7),
    house: 'Penanganan pembatalan mendadah & sepihak perusahaan',
},
{
    monarch: 'Pemetaan mahasiswa',
    start: new Date(2021, 5, 15),
    end: new Date(2021, 6, 7),
    house: 'Pemetaan/ mapping mahasiswa - perusahaan',
},
{
    monarch: 'Waiting Respon',
    start: new Date(2021, 4, 1),
    end: new Date(2021, 5, 28),
    house: 'Waiting Respon, merekap perusahaan yang fix menerima KP/PKL',
},
{
    monarch: 'Pengiriman surat penjagaan',
    start: new Date(2021, 3, 21),
    end: new Date(2021, 5, 14),
    house: 'Pengiriman surat penjagaan Penerimaan KP/PKL',
},
{
    monarch: 'Pencarian Perusahaan',
    start: new Date(2021, 3, 1),
    end: new Date(2021, 5, 7),
    house: 'Pencarian Perusahaan tujuan KP/PKL',
},
{
    monarch: 'Pengumpulan CV',
    start: new Date(2021, 3, 8),
    end: new Date(2021, 4, 7),
    house: 'Pengumpulan CV',
},
{
    monarch: 'Sosialisasi 1',
    start: new Date(2021, 3, 1),
    end: new Date(2021, 3, 7),
    house: 'Sosialisasi 1 (Mekanisme + Prosedur KP/PKL',
}, 
]
export default data
