import React from 'react'
import CIcon from '@coreui/icons-react'
import {
  cilBell,
  cilCalculator,
  cilChartPie,
  cilCursor,
  cilDrop,
  cilNotes,
  cilPencil,
  cilPuzzle,
  cilSpeedometer,
  cilStar,
} from '@coreui/icons'
import { CNavGroup, CNavItem, CNavTitle } from '@coreui/react'

const _nav = [
  // ================= PANITIA ===============================
  {
    component: CNavItem,
    name: 'Dashboard',
    to: '/dashboard',
    icon: <CIcon icon={cilSpeedometer} customClassName="nav-icon" />,
    role: 'panitia',
  },
  {
    component: CNavTitle,
    name: 'Data Mahasiswa',
    role: 'panitia',
  },
  {
    component: CNavItem,
    name: 'Rekap CV',
    to: '/rekapCV',
    icon: <CIcon icon={cilSpeedometer} customClassName="nav-icon" />,
    role: 'panitia',
  },
  {
    component: CNavItem,
    name: 'Rekap Minat',
    to: '/rekapMinat',
    icon: <CIcon icon={cilSpeedometer} customClassName="nav-icon" />,
    role: 'panitia',
  },
  {
    component: CNavGroup,
    name: 'Pemetaan Mahasiswa',
    to: '/pemetaan',
    icon: <CIcon icon={cilPuzzle} customClassName="nav-icon" />,
    role: 'panitia',
    items: [
      {
        component: CNavItem,
        name: 'Perangkingan Mahasiswa',
        to: '/pemetaan/perangkingan',
        role: 'panitia',
      },
      {
        component: CNavItem,
        name: 'Finalisasi Pemetaan',
        to: '/pemetaan/finalisasi',
        role: 'panitia',
      },
      {
        component: CNavItem,
        name: 'Hasil Pemetaan',
        to: '/pemetaan/hasil',
        role: 'panitia',
      },
    ],
  },
  {
    component: CNavTitle,
    name: 'Data Perusahaan',
    role: 'panitia',
  },
  {
    component: CNavItem,
    name: 'List Perusahaan',
    to: '/listPerusahaan',
    icon: <CIcon icon={cilSpeedometer} customClassName="nav-icon" />,
    role: 'panitia',
  },
  {
    component: CNavItem,
    name: 'Pengajuan Perusahaan',
    to: '/pengajuanPerusahaan',
    icon: <CIcon icon={cilSpeedometer} customClassName="nav-icon" />,
    role: 'panitia',
  },
  {
    component: CNavTitle,
    name: 'Lain - lain',
    role: 'panitia',
  },
  {
    component: CNavGroup,
    name: 'History Data KP/PKL',
    to: '/historyData',
    icon: <CIcon icon={cilPuzzle} customClassName="nav-icon" />,
    role: 'panitia',
    items: [
      {
        component: CNavItem,
        name: 'Pengajuan Perusahaan',
        to: '/history/pengajuanPerusahaan',
        role: 'panitia',
      },
      {
        component: CNavItem,
        name: 'Pre-requisite',
        to: '/history/preRequisite',
        role: 'panitia',
      },
      {
        component: CNavItem,
        name: 'CV',
        to: '/history/cv',
        role: 'panitia',
      },
      {
        component: CNavItem,
        name: 'Minat',
        to: '/history/minat',
        role: 'panitia',
      },
      {
        component: CNavItem,
        name: 'Hasil Pemetaan',
        to: '/history/hasilPemetaan',
        role: 'panitia',
      },
      {
        component: CNavItem,
        name: 'Evaluasi Perusahaan',
        to: '/history/evaluasiPerusahaan',
        role: 'panitia',
      },
      {
        component: CNavItem,
        name: 'Feedback Perusahaan',
        to: '/history/feedbackPerusahaan',
        role: 'panitia',
      },
    ],
  },
  {
    component: CNavItem,
    name: 'Pengelolaan Akun',
    to: '/pengelolaanAkun',
    icon: <CIcon icon={cilSpeedometer} customClassName="nav-icon" />,
    role: 'panitia',
  },
  {
    component: CNavItem,
    name: 'Pengelolaan Kompetensi',
    to: '/pengelolaanKompetensi',
    icon: <CIcon icon={cilSpeedometer} customClassName="nav-icon" />,
    role: 'panitia',
  },
  {
    component: CNavItem,
    name: 'Pengelolaan Bobot Kriteria Perangkingan',
    to: '/pengelolaanBobotKriteria',
    icon: <CIcon icon={cilSpeedometer} customClassName="nav-icon" />,
    role: 'panitia',
  },
  {
    component: CNavItem,
    name: 'Pengelolaan Kriteria Perusahaan',
    to: '/pengelolaanKriteriaPerusahaan',
    icon: <CIcon icon={cilSpeedometer} customClassName="nav-icon" />,
    role: 'panitia',
  },
  {
    component: CNavItem,
    name: 'Pengelolaan Aspek Pertanyaan Evaluasi',
    to: '/pengelolaanAspekPertanyaan',
    icon: <CIcon icon={cilSpeedometer} customClassName="nav-icon" />,
    role: 'panitia',
  },
  {
    component: CNavItem,
    name: 'Setting Lainnya',
    to: '/settingLainnya',
    icon: <CIcon icon={cilSpeedometer} customClassName="nav-icon" />,
    role: 'panitia',
  },

  // ================= Peserta ===============================
  {
    component: CNavItem,
    name: 'Dashboard',
    to: '/dashboard',
    icon: <CIcon icon={cilSpeedometer} customClassName="nav-icon" />,
    role: 'peserta',
  },
  {
    component: CNavTitle,
    name: 'Menu Mahasiswa',
    role: 'peserta',
  },
  {
    component: CNavItem,
    name: 'Pengumpulan CV',
    to: '/pengumpulanCV',
    icon: <CIcon icon={cilDrop} customClassName="nav-icon" />,
    role: 'peserta',
  },
  {
    component: CNavItem,
    name: 'Pemilihan Perusahaan',
    to: '/pemilihanPerusahaan',
    icon: <CIcon icon={cilDrop} customClassName="nav-icon" />,
    role: 'peserta',
  },
  {
    component: CNavItem,
    name: 'List Perusahaan',
    to: '/listPerusahaan',
    icon: <CIcon icon={cilDrop} customClassName="nav-icon" />,
    role: 'peserta',
  },
  {
    component: CNavItem,
    name: 'Pemetaan Mahasiswa',
    to: '/pemetaanMahasiswa',
    icon: <CIcon icon={cilDrop} customClassName="nav-icon" />,
    role: 'peserta',
  },
  {
    component: CNavTitle,
    name: 'Lain - lain',
    role: 'peserta',
  },
  {
    component: CNavItem,
    name: 'Pengelolaan Kompetensi',
    to: '/pengelolaan Kompetensi',
    icon: <CIcon icon={cilDrop} customClassName="nav-icon" />,
    role: 'peserta',
  },

  // ================= Perusahaan ===============================
  {
    component: CNavItem,
    name: 'Dashboard',
    to: '/dashboard',
    icon: <CIcon icon={cilSpeedometer} customClassName="nav-icon" />,
    role: 'perusahaan',
  },
  {
    component: CNavTitle,
    name: 'Menu Perusahaan',
    role: 'perusahaan',
  },
  {
    component: CNavItem,
    name: 'Data Mahasiswa KP/PKL',
    to: '/dataMahasiswa',
    icon: <CIcon icon={cilDrop} customClassName="nav-icon" />,
    role: 'perusahaan',
  },
  {
    component: CNavItem,
    name: 'Formulir Kesediaan Perusahaan',
    to: '/formulirKesediaan',
    icon: <CIcon icon={cilDrop} customClassName="nav-icon" />,
    role: 'perusahaan',
  },
  {
    component: CNavItem,
    name: 'Formulir Evaluasi Peserta',
    to: '/formulirEvaluasi',
    icon: <CIcon icon={cilDrop} customClassName="nav-icon" />,
    role: 'perusahaan',
  },
  {
    component: CNavItem,
    name: 'Formulir Feedback Pelaksanaan KP/PKL',
    to: '/formulirFeedback',
    icon: <CIcon icon={cilDrop} customClassName="nav-icon" />,
    role: 'perusahaan',
  },
  {
    component: CNavTitle,
    name: 'Lain - lain',
    role: 'perusahaan',
  },
  {
    component: CNavGroup,
    name: 'History Data KP/PKL',
    to: '/history',
    icon: <CIcon icon={cilPuzzle} customClassName="nav-icon" />,
    role: 'perusahaan',
    items: [
      {
        component: CNavItem,
        name: 'Data Mahasiswa KP/PKL',
        to: '/history/dataMahasiswa',
        role: 'perusahaan',
      },
      {
        component: CNavItem,
        name: 'Pre-requisite',
        to: '/history/preRequisite',
        role: 'perusahaan',
      },
      {
        component: CNavItem,
        name: 'Evaluasi Peserta',
        to: '/history/evaluasi',
        role: 'perusahaan',
      },
      {
        component: CNavItem,
        name: 'Feedback Pelaksanaan KP/PKL',
        to: '/history/feedback',
        role: 'perusahaan',
      },
    ],
  },
  {
    component: CNavItem,
    name: 'Pengelolaan Kompetensi',
    to: '/pengelolaanKompetensi',
    icon: <CIcon icon={cilDrop} customClassName="nav-icon" />,
    role: 'perusahaan',
  },

  // ================= Lain - lain  ===============================
  {
    component: CNavTitle,
    name: 'Theme',
    role: '',
  },
  {
    component: CNavItem,
    name: 'Colors',
    to: '/theme/colors',
    icon: <CIcon icon={cilDrop} customClassName="nav-icon" />,
    role: '',
  },
  {
    component: CNavItem,
    name: 'Typography',
    to: '/theme/typography',
    icon: <CIcon icon={cilPencil} customClassName="nav-icon" />,
    role: '',
  },
  {
    component: CNavTitle,
    name: 'Components',
    role: '',
  },
  {
    component: CNavGroup,
    name: 'Base',
    to: '/base',
    icon: <CIcon icon={cilPuzzle} customClassName="nav-icon" />,
    role: '',
    items: [
      {
        component: CNavItem,
        name: 'Accordion',
        to: '/base/accordion',
        role: '',
      },
      {
        component: CNavItem,
        name: 'Breadcrumb',
        to: '/base/breadcrumbs',
        role: '',
      },
      {
        component: CNavItem,
        name: 'Cards',
        to: '/base/cards',
        role: '',
      },
      {
        component: CNavItem,
        name: 'Carousel',
        to: '/base/carousels',
        role: '',
      },
      {
        component: CNavItem,
        name: 'Collapse',
        to: '/base/collapses',
        role: '',
      },
      {
        component: CNavItem,
        name: 'List group',
        to: '/base/list-groups',
        role: '',
      },
      {
        component: CNavItem,
        name: 'Navs & Tabs',
        to: '/base/navs',
        role: '',
      },
      {
        component: CNavItem,
        name: 'Pagination',
        to: '/base/paginations',
        role: '',
      },
      {
        component: CNavItem,
        name: 'Popovers',
        to: '/base/popovers',
        role: '',
      },
      {
        component: CNavItem,
        name: 'Progress',
        to: '/base/progress',
        role: '',
      },
      {
        component: CNavItem,
        name: 'Spinners',
        to: '/base/spinners',
        role: '',
      },
      {
        component: CNavItem,
        name: 'Tables',
        to: '/base/tables',
        role: '',
      },
      {
        component: CNavItem,
        name: 'Tooltips',
        to: '/base/tooltips',
        role: '',
      },
    ],
  },
  {
    component: CNavGroup,
    name: 'Buttons',
    to: '/buttons',
    icon: <CIcon icon={cilCursor} customClassName="nav-icon" />,
    role: '',
    items: [
      {
        component: CNavItem,
        name: 'Buttons',
        to: '/buttons/buttons',
        role: '',
      },
      {
        component: CNavItem,
        name: 'Buttons groups',
        to: '/buttons/button-groups',
        role: '',
      },
      {
        component: CNavItem,
        name: 'Dropdowns',
        to: '/buttons/dropdowns',
        role: '',
      },
    ],
  },
  {
    component: CNavGroup,
    name: 'Forms',
    icon: <CIcon icon={cilNotes} customClassName="nav-icon" />,
    role: '',
    items: [
      {
        component: CNavItem,
        name: 'Form Control',
        to: '/forms/form-control',
        role: '',
      },
      {
        component: CNavItem,
        name: 'Select',
        to: '/forms/select',
        role: '',
      },
      {
        component: CNavItem,
        name: 'Checks & Radios',
        to: '/forms/checks-radios',
        role: '',
      },
      {
        component: CNavItem,
        name: 'Range',
        to: '/forms/range',
        role: '',
      },
      {
        component: CNavItem,
        name: 'Input Group',
        to: '/forms/input-group',
        role: '',
      },
      {
        component: CNavItem,
        name: 'Floating Labels',
        to: '/forms/floating-labels',
        role: '',
      },
      {
        component: CNavItem,
        name: 'Layout',
        to: '/forms/layout',
        role: '',
      },
      {
        component: CNavItem,
        name: 'Validation',
        to: '/forms/validation',
        role: '',
      },
    ],
  },
  {
    component: CNavItem,
    name: 'Charts',
    to: '/charts',
    icon: <CIcon icon={cilChartPie} customClassName="nav-icon" />,
    role: '',
  },
  {
    component: CNavGroup,
    name: 'Icons',
    icon: <CIcon icon={cilStar} customClassName="nav-icon" />,
    items: [
      {
        component: CNavItem,
        name: 'CoreUI Free',
        to: '/icons/coreui-icons',
        badge: {
          color: 'success',
          text: 'NEW',
        },
        role: '',
      },
      {
        component: CNavItem,
        name: 'CoreUI Flags',
        to: '/icons/flags',
        role: '',
      },
      {
        component: CNavItem,
        name: 'CoreUI Brands',
        to: '/icons/brands',
        role: '',
      },
    ],
  },
  {
    component: CNavGroup,
    name: 'Notifications',
    icon: <CIcon icon={cilBell} customClassName="nav-icon" />,
    role: '',
    items: [
      {
        component: CNavItem,
        name: 'Alerts',
        to: '/notifications/alerts',
        role: '',
      },
      {
        component: CNavItem,
        name: 'Badges',
        to: '/notifications/badges',
        role: '',
      },
      {
        component: CNavItem,
        name: 'Modal',
        to: '/notifications/modals',
        role: '',
      },
      {
        component: CNavItem,
        name: 'Toasts',
        to: '/notifications/toasts',
        role: '',
      },
    ],
  },
  {
    component: CNavItem,
    name: 'Widgets',
    to: '/widgets',
    icon: <CIcon icon={cilCalculator} customClassName="nav-icon" />,
    role: '',
    badge: {
      color: 'info',
      text: 'NEW',
    },
  },
  {
    component: CNavTitle,
    name: 'Extras',
  },
  {
    component: CNavGroup,
    name: 'Pages',
    icon: <CIcon icon={cilStar} customClassName="nav-icon" />,
    role: '',
    items: [
      {
        component: CNavItem,
        name: 'Login',
        to: '/login',
        role: '',
      },
      {
        component: CNavItem,
        name: 'Register',
        to: '/register',
        role: '',
      },
      {
        component: CNavItem,
        name: 'Error 404',
        to: '/404',
        role: '',
      },
      {
        component: CNavItem,
        name: 'Error 500',
        to: '/500',
        role: '',
      },
    ],
  },
]

export default _nav
